---
output:
  pdf_document: default
  html_document: default
---
# (APPENDIX) Appendix {.unnumbered}

# Software

To study and learn the content presented in this book, you will be required to download and install a few computer standalone applications. Below, you will learn how to download and install these applications in your machine.

## JASP {#jasp}

The open-source statistical package JASP [@JASP2020] will be used to demonstrate the statistical analyses covered in this book.

### Prerequisites

- Windows, MacOS, or Linux

### Download and installation {#jasp-install}

Please, follow the instructions found in [@goss-sampsonStatisticalAnalysisJASP2020] to install JASP in your device.

# Assignment Examples {#assignment-examples}

In this section, I provide several examples of assignments instructors can use when teaching introductory statistics courses to undergraduate or graduate students.

## Homeworks

### JASP

**Learning objectives**

1. create filters in JASP
2. calculate measures of central tendency and variability in JASP
3. differentiate between descriptive and inferential statistics
4. create and interpret histograms and boxplots

Example 1: [instructions](assignments/jasp-01.html)

### Descriptive Statistics

**Learning objectives**

1.	Differentiate between independent and dependent variables
2.	Assign the correct data level to variables (nominal, ordinal, and scale)
3.	Create and compute new variables in JASP
4.	Select and deselect cases in JASP
5.	Create and interpret histograms, boxplots, and Q-Q Plots

Example 1: [Instructions](assignments/descriptive-01.html)

## Projects

* Example 1: [instructions](assignments/project-01.html)

----

# Symbols and Equations {#symbols-equations}

## Symbols

Below are some of the symbols I will use throughout this book to refer to various statistical terms.

+-----------+-------------------------------+---------------------------+
| Symbol    | Meaning                       | Reference to a value in a |
+:==========+:==============================+:==========================+
| n         | Sample size                   | Sample                    |
+-----------+-------------------------------+---------------------------+
| $\bar{x}$ | Sample mean                   | Sample                    |
+-----------+-------------------------------+---------------------------+
| $\mu$     | Population mean               | Population                |
+-----------+-------------------------------+---------------------------+
| s         | Sample standard deviation     | Sample                    |
+-----------+-------------------------------+---------------------------+
| $\sigma$  | Population standard deviation | Population                |
+-----------+-------------------------------+---------------------------+
| *r*       | Pearson correlation           | Sample                    |
+-----------+-------------------------------+---------------------------+
| $\rho$    | Pearson correlation           | Population                |
+-----------+-------------------------------+---------------------------+
| x, z      | Observed data value           | Population                |
+-----------+-------------------------------+---------------------------+

## Equations

Although, in general, you will not be required to perform calculations by hand while following the tutorials found in this book, it is worth getting familiar with some key equations.

**Standard error of the mean (SEM)**

\begin{equation}
\sigma_{\bar{x}}=\frac{\sigma}{\sqrt{n}}
(#eq:sem)
\end{equation}

where:

- $\sigma_{\bar{x}}$ refers standard deviation of the sample means indicated by $\bar{x}$.
- $n$ refers to the sample size.
- $\sigma$ refers to the population standard deviation.

------------------------------------------------------------------------

**Z-test (**$\sigma$ is Known)

A test used to compare a sample mean with a population value when the standard deviation of the population ($\sigma$) is known and the sample size (n) is larger than 30.

\begin{equation}
\label{standard normal value}
z = \frac{x - \mu}{\sigma}
(#eq:ztest)
\end{equation}

where:

- $\bar{x}$ refers to the sample mean.
- $\mu$ refers to the population mean.
- $\sigma$ refers to the population standard deviation.
- $n$ refers to the sample size.

------------------------------------------------------------------------

**One-Sample t-test (**$\sigma$ is Unknown)

\begin{equation}
\label{testing a mean sigma unknown}(\#eq:t-test-one) 
t = \frac{\bar{x}-\mu}{\frac{s}{\sqrt{n}}}
(#eq:onet)
\end{equation}

with $n-1$ degrees of freedom where:

- $\bar{x}$ is the sample mean.
- $\mu$ is the hypothesized population mean.
- $s$ is the sample standard deviation.
- $n$ is the number of observations in the sample.

------------------------------------------------------------------------

**Standard Deviation of Differences** - Two-Sample Test

\begin{equation}
s_{d} = \sqrt{\frac{\sum(d - \bar{d})^2}{n - 1}}
(#eq:??)
\end{equation}

where:

- $\bar{d}$ is the mean of the difference between the paired or related observations.
- $s_{d}$ is the standard deviation of the differences between the paired or related observations.
- $n$ is the number of paired observations.

------------------------------------------------------------------------

**Coefficient of Variation**

\begin{equation}
\text{CV} = \frac{s}{\bar{x}}(100)
  (#eq:binom)
\end{equation}

Note: multiplying by 100 converts the decimal to a percent

where:

- $s$ is the sample standard deviation.
- $\bar{x}$ is the sample mean.

----

