graph LR
A(Is the thigh of the<br>suspended leg in a<br>vertical position<br>with knee flexed at<br>90 degrees or less?)-- Yes -->B[Does the foot of the<br>suspended leg cross<br>the line of the support<br>leg like a pendulum?]
A-- No -->C[Is the suspended leg<br>held in front of the<br>body?]
B-- Yes -->D(Level 4)
B-- No -->E(Level 3)
C-- No -->F(Level 2)
C-- Yes -->G(Level 1)
