--- 
title: "Teaching Stats with JASP: A Guide to Data Analysis & Interpretation"
author: "Ovande Furtado, Jr., Ph.D."
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
documentclass: book
bibliography:
- book.bib
- packages.bib
biblio-style: apalike
csl: apa-numeric-superscript-brackets.csl
link-citations: yes
description: A Guide to Data Analysis & Interpretation
site: bookdown::bookdown_site
---

# Preface {.unnumbered}

This is a companion book[^index-1] used in a course[^index-2] I teach at [Cal State Northridge](https://academics.csun.edu/faculty/ovande.furtado){target="_blank"}. This book is comprised of step-by-step tutorials showing how to perform statistical analysis with [JASP](#jasp).

[^index-1]: The online version of this book is free to read and licensed under [Creative Commons Attribution-NonCommercial 4.0 International License](http://creativecommons.org/licenses/by-nc/4.0/){target="_blank"}.

[^index-2]: KIN610 - Quantitative Analysis of Research in Kinesiology

Future versions of this book will contain topics related to **hypothesis testing**, **descriptive and inferential statistics**, etc. The goal is for this book to evolve into a textbook that may be used in Introductory Statistics courses taught at the undergraduate or graduate levels.

**Updates**

I announce major updates made to this book on Twitter. For updates, follow me at ofurtado[^index-3]. Alternatively, you can subscribe to my blog [www.drfurtado.us](http://drfurtado.us){target="_blank"} for updates.

[^index-3]: <http://twitter.com/ofurtado>

**How to use this book**

To take full advantage of this book, I encourage you to download and install JASP (Section \@ref(jasp-install)). so that you can follow along. You will need to take some time to practice the tutorials using JASP. Besides, make sure to complete the challenge exercises you will encounter while studying the tutorials found throughout this book.

<!--chapter:end:index.Rmd-->

# (APPENDIX) Appendix {.unnumbered}

# Software

To study and learn the content presented in this book, you will be required to download and install a few computer standalone applications. Below, you will learn how to download and install these applications in your machine.

## JASP {#jasp}

The open-source statistical package JASP [@JASP2020] will be used to demonstrate the statistical analyses covered in this book.

### Prerequisites

- Windows, MacOS, or Linux

### Download and installation {#jasp-install}

Please, follow the instructions found in [@goss-sampsonStatisticalAnalysisJASP2020] to install JASP in your device.

# Assignment Examples

In this section, I provide several examples of assignments instructors can use when teaching introductory statistics courses to undergraduate or graduate students.

## Descriptive Statistics

* Example 1: [HTML](assignments/homework-example-01.html) | [Word](assignments/homework-example-01.docx) 

# Symbols and Equations {#symbols-equations}

## Symbols

Below are some of the symbols I will use throughout this book to refer to various statistical terms.

+-----------+-------------------------------+---------------------------+
| Symbol    | Meaning                       | Reference to a value in a |
+:==========+:==============================+:==========================+
| n         | Sample size                   | Sample                    |
+-----------+-------------------------------+---------------------------+
| $\bar{x}$ | Sample mean                   | Sample                    |
+-----------+-------------------------------+---------------------------+
| $\mu$     | Population mean               | Population                |
+-----------+-------------------------------+---------------------------+
| s         | Sample standard deviation     | Sample                    |
+-----------+-------------------------------+---------------------------+
| $\sigma$  | Population standard deviation | Population                |
+-----------+-------------------------------+---------------------------+
| *r*       | Pearson correlation           | Sample                    |
+-----------+-------------------------------+---------------------------+
| $\rho$    | Pearson correlation           | Population                |
+-----------+-------------------------------+---------------------------+
| x, z      | Observed data value           | Population                |
+-----------+-------------------------------+---------------------------+

## Equations

Although, in general, you will not be required to perform calculations by hand while following the tutorials found in this book, it is worth getting familiar with some key equations.

**Standard error of the mean (SEM)**

\begin{equation}
\sigma_{\bar{x}}=\frac{\sigma}{\sqrt{n}}
(#eq:sem)
\end{equation}

where:

- $\sigma_{\bar{x}}$ refers standard deviation of the sample means indicated by $\bar{x}$.
- $n$ refers to the sample size.
- $\sigma$ refers to the population standard deviation.

------------------------------------------------------------------------

**Z-test (**$\sigma$ is Known)

A test used to compare a sample mean with a population value when the standard deviation of the population ($\sigma$) is known and the sample size (n) is larger than 30.

\begin{equation}
\label{standard normal value}
z = \frac{x - \mu}{\sigma}
(#eq:ztest)
\end{equation}

where:

- $\bar{x}$ refers to the sample mean.
- $\mu$ refers to the population mean.
- $\sigma$ refers to the population standard deviation.
- $n$ refers to the sample size.

------------------------------------------------------------------------

**One-Sample t-test (**$\sigma$ is Unknown)

\begin{equation}
\label{testing a mean sigma unknown}(\#eq:t-test-one) t = 
\frac{\bar{x}-\mu}{\frac{s}{\sqrt{n}}}
(#eq:onet)
\end{equation}

with $n-1$ degrees of freedom where:

- $\bar{x}$ is the sample mean.
- $\mu$ is the hypothesized population mean.
- $s$ is the sample standard deviation.
- $n$ is the number of observations in the sample.

------------------------------------------------------------------------

**Standard Deviation of Differences** - Two-Sample Test

\begin{equation}
s_{d} = \sqrt{\frac{\sum(d - \bar{d})^2}{n - 1}}
(#eq:??)
\end{equation}

where:

- $\bar{d}$ is the mean of the difference between the paired or related observations.
- $s_{d}$ is the standard deviation of the differences between the paired or related observations.
- $n$ is the number of paired observations.

------------------------------------------------------------------------

**Coefficient of Variation**

\begin{equation}
\text{CV} = \frac{s}{\bar{x}}(100)
  (#eq:binom)
\end{equation}

Note: multiplying by 100 converts the decimal to a percent

where:

- $s$ is the sample standard deviation.
- $\bar{x}$ is the sample mean.

<!--chapter:end:appendix.Rmd-->

`r if (knitr::is_html_output()) '
# References {-}
'`

<!--chapter:end:06-references.Rmd-->

