---
title: "TSJ | Homework Example 1"
author: "Dr. Furtado"
header-includes: \linespread{1.05}
output:
  html_document:
    df_print: paged
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    latex_engine: pdflatex
    template: ../latex-assignment.tex
  word_document: default
geometry: margin=1in
affiliation: Department of Kinesiology, Cal State Northridge
email: ovandef@csun.edu
fontfamily: mathpazo
fontsize: 11pt
---

#### Learning objectives

1. create filters in JASP
2. calculate measures of central tendency and variability in JASP
3. differentiate between descriptive and inferential statistics
4. create and interpret histograms and boxplots

#### Dataset: download link will be available on Canvas

We will use a modified version of the NFL Combine data set (ref needed). The data set can be downloaded from this link: [https://osf.io/tbgfh/](https://osf.io/tbgfh/)

Note that you will be required to apply/remove filters when completing some of the required analysis for this assignment^[Refer to this link for help: https://bit.ly/37RPncf].

------------------------------------------------------------------------

Open the data set in JASP and proceed to answer the following questions^[Questions are worth 10 points]:

**Question 1**

**Filter**: apply a filter to `Position` so that only `Wide Receivers` (WR) and `Safety` (S) are included in this analysis.

For the variables `Heightin` and `Weightlbs`, compute the following: `mean`, `median`, `standard deviation`, `min`, `max`, and `sample size` (n).

Provide below the **Descriptive Statistics** Table:

```{=tex}
\begin{table}[h]
    \centering
    \caption{Descriptive Statistics - DEMONSTRATION}
    \label{tab:descriptiveStatistics}
    {
        \begin{tabular}{lrrrr}
            \toprule
            \multicolumn{1}{c}{} & \multicolumn{2}{c}{Heightin} & \multicolumn{2}{c}{Weightlbs} \\
            \cline{2-3}\cline{4-5}
             & S & WR & S & WR  \\
            \cmidrule[0.4pt]{1-5}
            Valid & 25 & 43 & 25 & 43  \\
            Missing & 0 & 0 & 0 & 0  \\
            Mean & 71.920 & 72.674 & 206.320 & 203.651  \\
            Median & 72.000 & 73.000 & 207.000 & 202.000  \\
            Std. Deviation & 1.681 & 1.835 & 7.609 & 11.284  \\
            Minimum & 69.000 & 69.000 & 191.000 & 182.000  \\
            Maximum & 76.000 & 76.000 & 218.000 & 234.000  \\
            \bottomrule
        \end{tabular}
    }
\end{table}
```

------------------------------------------------------------------------

**Question 2**

**Filter**: remove all filters before proceeding!

Considering the nature of both dependent variables used in Question 1 and assuming the distribution of scores for both variables are **approximating normality**, which measure of central tendency should be reported (mean, mode, or median)? Explain.

------------------------------------------------------------------------

**Question 3**

In questions 1, you calculated the measures of central tendency and variability, which fall under the category of descriptive statistics. Discuss the difference between **descriptive statistics** and **inferential statistics**. More complete answers will receive more points.

------------------------------------------------------------------------

**Question 4**

**Filter**: apply a filter to `Position` so that only `Quarterbacks` (QB) are included in this analysis.

Using the variable `BroadJumpin`, calculate the `range`, `standard deviation` and the `IQR` for Quarterbacks (QB) ONLY.

Provide below the **Descriptive Statistics** Table:

```{=tex}
\begin{table}[h]
    \centering
    \caption{Descriptive Statistics - DEMONSTRATION}
    \label{tab:descriptiveStatistics}
    {
        \begin{tabular}{lrrrr}
            \toprule
            \multicolumn{1}{c}{} & \multicolumn{2}{c}{Heightin} & \multicolumn{2}{c}{Weightlbs} \\
            \cline{2-3}\cline{4-5}
             & S & WR & S & WR  \\
            \cmidrule[0.4pt]{1-5}
            Valid & 25 & 43 & 25 & 43  \\
            Missing & 0 & 0 & 0 & 0  \\
            Mean & 71.920 & 72.674 & 206.320 & 203.651  \\
            Median & 72.000 & 73.000 & 207.000 & 202.000  \\
            Std. Deviation & 1.681 & 1.835 & 7.609 & 11.284  \\
            Minimum & 69.000 & 69.000 & 191.000 & 182.000  \\
            Maximum & 76.000 & 76.000 & 218.000 & 234.000  \\
            \bottomrule
        \end{tabular}
    }
\end{table}
```

------------------------------------------------------------------------

**Question 5**

**Filter**: remove all filters before proceeding!

In Question 1, you were asked to calculate the standard deviation of height (inches) and weight (lbs). Suppose you want to compare the `standard deviations` of `height` and `weight`. How the two standard deviations compare?

------------------------------------------------------------------------

**Question 6**

When calculating the sample variance and standard deviation, JASP uses `N-1` in the denominator (see below). In your own words, explain why `N-1` is used instead of `N`.

Standard Deviation equation for the sample:

$\sigma = \sqrt{\frac{\sum (x - \mu)^2}{N-1}}$

Variance equation for the sample:

$s^2 = \frac{\sum (x - \bar{x})^2}{N - 1}$

------------------------------------------------------------------------

**Question 7**

The `variance` and the `standard deviation` are the two most common measures of variability reported in research manuscripts. Let's say the manuscript you submitted for publication was returned by the editor. The editor-in-chief has asked you to report either the `variance` OR the `standard deviation`. Which one would you pick and why?

------------------------------------------------------------------------

**Question 8**

**Filter**: apply a filter to `Status` so that **only** `Year 2` is included in this analysis.

The variable "Status" refers to players who were either tested during the first or second year. Run an analysis to calculate the `mean`, and `standard deviation` for the variable `Shuttle`.

Provide below the **Descriptive Statistics** Table:

```{=tex}
\begin{table}[h]
    \centering
    \caption{Descriptive Statistics - DEMONSTRATION}
    \label{tab:descriptiveStatistics}
    {
        \begin{tabular}{lr}
            \toprule
             & Shuttle  \\
            \cmidrule[0.4pt]{1-2}
            Valid & 78  \\
            Missing & 42  \\
            Mean & 4.433  \\
            Std. Deviation & 0.266  \\
            \bottomrule
        \end{tabular}
    }
\end{table}
```

------------------------------------------------------------------------

**Question 9**

Create a histogram for the variable `Shuttle` and add the density line to it.

Provide the histogram create by JASP below and state whether the distribution of scores for `Shuttle` appears to be deviating or approximating normality. In this particular case, disregard other sources of normality (skewness, kurtosis, QQ-plots, Shapiro-Wilk test, etc.).

----

Provide below the **histogram** graph:

**Question 10**

Create a histogram for `Shuttle` using `ggplot2` as the color palette. Did the creation of the boxplot reveal any outliers? Explain.

Provide below the **boxblot** graph:
