---
title: "KIN 610 | Final Project - Template"
author: "Dr. Furtado"
header-includes: \linespread{1.05}
output:
  word_document: default
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    latex_engine: pdflatex
    template: ../latex-assignment.tex
  html_document:
    df_print: paged
geometry: margin=1in
affiliation: Department of Kinesiology, Cal State Northridge
email: ovandef@csun.edu
fontfamily: mathpazo
fontsize: 11pt
---

Your name: 

**Instructions**

Follow the steps found in the [project's instructions file](https://drfurtado.github.io/tsj/assignment-examples.html#projects). Then, use this word document to 

**Research Question**

Copy and paste your research question here...

----

**1) Dependent and Independent Variables**

Points: _____/30

Dependent variable(s)

Name: state and explain

Nature: state and explain

Normality
Zkurt: show your work
Zskew: show your work
Shapiro-Wilk value and p-value: text here

Histogram (copy and paste below)
Paste here...
Normal QQ plot (copy and paste below)
Paste here
Independent variable(s)
Name: state and explain
Levels: state and explain

2) Formulate the hypothesis(ses) for each of the dependent variable(s)
Points: _____/10

Prediction
Text here...
Ho
Symbol: text here
Written: text here
Ha
Symbol: text here
Written: text here

3) Choose the appropriate statistical analysis to test the hypothesis(ses)
Points: _____/10
Statistical Procedure: 
Provide at least 3 reasons you selected the procedure:
Reason one:
Reason two:
Reason three:

4) Output generated by SPSS
Points: _____/10
Nothing here; simply attach a clean version of the output containing the relevant tables and graphs generated by SPSS.

5) Interpret the results based on the output generated by SPSS
Points: _____/35

Statistical Analysis
Text here...
Results
Text here...
Conclusions
Text here...
Limitations
Text here...

6) Disclosures
The data set used for this project has been modified. Some of the variables have been fabricated. The conclusions provided here are limited to the scope of this assignment and should not be used to infer back to the population where the sample was taken from.

7) References following the 6th APA Style
Points: _____/5
References here...



